import {CONFIG} from './config.js';
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>{if(n==null||Number.isNaN(+n))return '—'; return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(+n)};
const pct=n=>`${Math.round(n||0)}%`; const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const state={answers:JSON.parse(localStorage.getItem('pwp_answers')||'{}'),current:0,contact:JSON.parse(localStorage.getItem('pwp_contact')||'null'),results:null,ref:new URLSearchParams(location.search).get('ref')||'organic'};
const MODULES=[
{id:'family',name:'Família e Contexto',icon:'◎'}, {id:'income',name:'Renda e Fluxo Financeiro',icon:'▥'}, {id:'liquidity',name:'Liquidez e Reserva',icon:'◫'}, {id:'incomeProtection',name:'Proteção de Renda',icon:'◇'}, {id:'familyProtection',name:'Proteção Familiar',icon:'♡'}, {id:'health',name:'Saúde',icon:'✚'}, {id:'wealth',name:'Patrimônio e Sucessão',icon:'◉'}, {id:'future',name:'Futuro e Internacionalização',icon:'↗'}
];
const O=(label,value=label)=>({label,value});
const Q=[
{id:'age',m:'family',t:'Qual é a sua idade?',type:'number',placeholder:'Ex.: 46',min:18,max:90,why:'A fase de vida ajuda a contextualizar dependentes, objetivos e horizonte de planejamento.'},
{id:'marital',m:'family',t:'Qual é o seu estado civil?',type:'single',o:['Solteiro(a)','Casado(a)','União estável','Divorciado(a)','Viúvo(a)'].map(x=>O(x))},
{id:'dependents',m:'family',t:'Quem depende financeiramente de você hoje?',type:'multi',o:['Cônjuge / parceiro(a)','Filhos','Pais','Outros familiares','Ninguém'].map(x=>O(x)),why:'Dependência financeira é central para estimar necessidade de proteção familiar.'},
{id:'children',m:'family',t:'Quantos filhos dependem financeiramente de você?',type:'single',show:a=>(a.dependents||[]).includes('Filhos'),o:['1','2','3','4 ou mais'].map(x=>O(x))},
{id:'youngest',m:'family',t:'Qual é a idade aproximada do filho mais novo?',type:'single',show:a=>(a.dependents||[]).includes('Filhos'),o:['0–5','6–12','13–17','18–24','25+'].map(x=>O(x))},
{id:'country',m:'family',t:'Onde você reside atualmente?',type:'single',o:['Brasil','Estados Unidos','México','Outro país da América Latina','Europa','Outro'].map(x=>O(x))},
{id:'occupation',m:'family',t:'Qual opção melhor descreve sua atividade principal?',type:'single',o:['Empresário(a)','Médico(a) / profissional da saúde','Profissional liberal','Executivo(a)','Assalariado(a)','Investidor(a)','Aposentado(a)','Outro'].map(x=>O(x))},
{id:'businessShare',m:'family',t:'Qual é aproximadamente a sua participação na empresa?',type:'single',show:a=>a.occupation==='Empresário(a)',o:['Até 25%','26–50%','51–75%','76–100%'].map(x=>O(x))},
{id:'businessDependence',m:'family',t:'A empresa continuaria operando normalmente por 12 meses sem a sua atuação?',type:'single',show:a=>a.occupation==='Empresário(a)',o:['Sim','Provavelmente sim','Não sei','Provavelmente não','Não'].map(x=>O(x))},
{id:'partners',m:'family',t:'Existem outros sócios na empresa?',type:'single',show:a=>a.occupation==='Empresário(a)',o:['Sim','Não'].map(x=>O(x))},
{id:'shareholderAgreement',m:'family',t:'Existe acordo societário para morte ou incapacidade de um sócio?',type:'single',show:a=>a.occupation==='Empresário(a)'&&a.partners==='Sim',o:['Sim','Parcialmente','Não','Não sei'].map(x=>O(x))},
{id:'buySellFunding',m:'family',t:'Existe capital ou seguro planejado para compra da participação de um sócio?',type:'single',show:a=>a.occupation==='Empresário(a)'&&a.partners==='Sim',o:['Sim','Não','Não sei'].map(x=>O(x))},

{id:'income',m:'income',t:'Qual é a renda familiar mensal aproximada?',type:'single',o:[O('Até R$ 20 mil',15000),O('R$ 20–40 mil',30000),O('R$ 40–70 mil',55000),O('R$ 70–120 mil',95000),O('R$ 120–250 mil',180000),O('R$ 250–500 mil',350000),O('R$ 500 mil+',600000)]},
{id:'expenses',m:'income',t:'Quanto sua família precisa por mês para manter o padrão de vida atual?',type:'single',o:[O('Até R$ 15 mil',12000),O('R$ 15–30 mil',22500),O('R$ 30–50 mil',40000),O('R$ 50–80 mil',65000),O('R$ 80–150 mil',115000),O('R$ 150 mil+',180000)]},
{id:'workDependency',m:'income',t:'Quanto da renda familiar depende diretamente da sua atividade profissional?',type:'single',o:[O('Até 25%',20),O('26–50%',40),O('51–75%',65),O('76–99%',87),O('100%',100)]},
{id:'otherIncomeTypes',m:'income',t:'Sua família possui outras fontes recorrentes de renda?',type:'multi',o:['Salário do cônjuge','Aluguéis','Dividendos / investimentos','Empresa','Aposentadoria','Outras','Não'].map(x=>O(x))},
{id:'independentIncome',m:'income',t:'Se você parasse de trabalhar hoje, aproximadamente quanto da renda familiar continuaria entrando?',type:'single',o:[O('Nada',0),O('Até R$ 10 mil',7500),O('R$ 10–25 mil',17500),O('R$ 25–50 mil',37500),O('R$ 50–100 mil',75000),O('R$ 100 mil+',120000)]},
{id:'incomeStability',m:'income',t:'Como você considera a previsibilidade da sua renda nos próximos 24 meses?',type:'single',o:['Muito previsível','Previsível','Variável','Muito variável'].map(x=>O(x))},

{id:'liquidAssets',m:'liquidity',t:'Quanto sua família possui em recursos de alta liquidez?',type:'single',o:[O('Até R$ 50 mil',35000),O('R$ 50–150 mil',100000),O('R$ 150–300 mil',225000),O('R$ 300–600 mil',450000),O('R$ 600 mil–1,5 mi',1000000),O('R$ 1,5–5 mi',3000000),O('R$ 5 mi+',7000000)]},
{id:'emergencyReserve',m:'liquidity',t:'Existe uma reserva específica para emergências?',type:'single',o:['Sim','Não','Não sei dizer'].map(x=>O(x))},
{id:'runwaySelf',m:'liquidity',t:'Sem renda do trabalho, por quanto tempo sua família manteria o padrão de vida sem vender imóveis ou empresa?',type:'single',o:[O('Menos de 3 meses',2),O('3–6 meses',4.5),O('6–12 meses',9),O('12–24 meses',18),O('Mais de 24 meses',30)]},
{id:'restrictedLiquidity',m:'liquidity',t:'Parte relevante dos recursos possui restrição de resgate?',type:'single',o:['Sim','Não','Não sei'].map(x=>O(x))},
{id:'debts',m:'liquidity',t:'Você possui dívidas ou obrigações financeiras relevantes?',type:'multi',o:['Financiamento imobiliário','Financiamento empresarial','Empréstimos','Garantias pessoais','Outras','Não'].map(x=>O(x))},
{id:'debtAmount',m:'liquidity',t:'Qual o saldo aproximado dessas obrigações?',type:'single',show:a=>(a.debts||[]).some(x=>x!=='Não'),o:[O('Até R$ 250 mil',150000),O('R$ 250–750 mil',500000),O('R$ 750 mil–2 mi',1350000),O('R$ 2–5 mi',3500000),O('R$ 5 mi+',7000000)]},

{id:'abilityDependence',m:'incomeProtection',t:'Sua renda depende da sua capacidade física ou intelectual de trabalhar?',type:'single',o:['Muito','Bastante','Parcialmente','Pouco','Não'].map(x=>O(x))},
{id:'incomeAfterDisabilityPct',m:'incomeProtection',t:'Se você ficasse impossibilitado de trabalhar por 12 meses, qual percentual da sua renda atual continuaria existindo?',type:'single',o:[O('0%',0),O('Até 25%',20),O('25–50%',40),O('50–75%',65),O('75%+',85)]},
{id:'disabilityCover',m:'incomeProtection',t:'Você possui proteção financeira específica para incapacidade ou invalidez?',type:'single',o:['Sim','Não','Não sei'].map(x=>O(x))},
{id:'disabilityMonthly',m:'incomeProtection',t:'Qual renda mensal aproximada essa proteção oferece?',type:'single',show:a=>a.disabilityCover==='Sim',o:[O('Até R$ 10 mil',7500),O('R$ 10–25 mil',17500),O('R$ 25–50 mil',37500),O('R$ 50–100 mil',75000),O('R$ 100 mil+',120000),O('Não sei',0)]},
{id:'disabilityLump',m:'incomeProtection',t:'Existe também um capital único em caso de invalidez?',type:'single',show:a=>a.disabilityCover==='Sim',o:[O('Não',0),O('Até R$ 500 mil',300000),O('R$ 500 mil–1 mi',750000),O('R$ 1–3 mi',2000000),O('R$ 3 mi+',4500000),O('Não sei',0)]},
{id:'employerCover',m:'incomeProtection',t:'Seu empregador ou empresa oferece proteção adicional?',type:'single',o:['Sim','Não','Não sei','Não se aplica'].map(x=>O(x))},

{id:'lifeCover',m:'familyProtection',t:'Você possui seguro de vida?',type:'single',o:['Sim','Não','Não sei'].map(x=>O(x))},
{id:'lifeCapital',m:'familyProtection',t:'Qual o capital total aproximado das coberturas de vida?',type:'single',show:a=>a.lifeCover==='Sim',o:[O('Até R$ 500 mil',300000),O('R$ 500 mil–1 mi',750000),O('R$ 1–3 mi',2000000),O('R$ 3–5 mi',4000000),O('R$ 5–10 mi',7500000),O('R$ 10 mi+',12000000),O('Não sei',0)]},
{id:'lifeReview',m:'familyProtection',t:'Quando essa proteção foi revisada pela última vez?',type:'single',show:a=>a.lifeCover==='Sim',o:['Menos de 1 ano','1–3 anos','3–5 anos','Mais de 5 anos','Nunca'].map(x=>O(x))},
{id:'beneficiaries',m:'familyProtection',t:'Os beneficiários das suas coberturas estão atualizados?',type:'single',show:a=>a.lifeCover==='Sim',o:['Sim','Não','Não sei'].map(x=>O(x))},
{id:'familyYears',m:'familyProtection',t:'Em sua ausência, por quanto tempo você gostaria que sua família mantivesse o padrão de vida?',type:'single',o:[O('1 ano',1),O('3 anos',3),O('5 anos',5),O('10 anos',10),O('Até a independência dos filhos',12),O('Outro horizonte',8)]},
{id:'protectedGoals',m:'familyProtection',t:'Quais objetivos deveriam estar protegidos independentemente do que aconteça?',type:'multi',o:['Educação dos filhos','Moradia','Aposentadoria do cônjuge','Pagamento de dívidas','Suporte aos pais','Continuidade empresarial','Legado','Outros'].map(x=>O(x))},

{id:'healthPlan',m:'health',t:'Qual é sua estrutura atual de assistência médica?',type:'single',o:['SUS','Plano nacional','Plano nacional premium','Seguro internacional','Plano nacional + internacional','Nenhuma'].map(x=>O(x))},
{id:'globalHealth',m:'health',t:'Sua cobertura permite tratamento médico fora do Brasil?',type:'single',o:['Sim, globalmente','Em alguns países / situações','Apenas emergência','Não','Não sei'].map(x=>O(x))},
{id:'travelFreq',m:'health',t:'Com qual frequência você viaja internacionalmente?',type:'single',o:['Raramente','1–2 vezes por ano','3–5 vezes por ano','6+ vezes por ano'].map(x=>O(x))},
{id:'longAbroad',m:'health',t:'Você ou sua família passam períodos prolongados fora do país?',type:'single',o:['Sim','Não'].map(x=>O(x))},
{id:'childrenAbroad',m:'health',t:'Seus filhos estudam ou existe intenção de estudarem fora?',type:'single',show:a=>(a.dependents||[]).includes('Filhos'),o:['Sim','Planejamos','Talvez','Não'].map(x=>O(x))},
{id:'medicalLiquidity',m:'health',t:'Em um tratamento de alto custo não coberto, você teria liquidez sem comprometer objetivos importantes?',type:'single',o:['Sim, confortavelmente','Provavelmente','Não sei','Provavelmente não','Não'].map(x=>O(x))},

{id:'netWorth',m:'wealth',t:'Qual é o seu patrimônio total aproximado?',type:'single',o:[O('Até R$ 1 milhão',700000),O('R$ 1–5 milhões',3000000),O('R$ 5–10 milhões',7500000),O('R$ 10–20 milhões',15000000),O('R$ 20–50 milhões',35000000),O('R$ 50–100 milhões',75000000),O('R$ 100 milhões+',120000000)]},
{id:'businessConcentration',m:'wealth',t:'Qual percentual do patrimônio está relacionado à sua própria empresa?',type:'single',o:[O('0%',0),O('Até 25%',20),O('26–50%',40),O('51–75%',65),O('76%+',85)]},
{id:'brazilConcentration',m:'wealth',t:'Qual percentual do patrimônio está localizado no Brasil?',type:'single',o:[O('Até 25%',20),O('26–50%',40),O('51–75%',65),O('76–90%',83),O('Mais de 90%',95)]},
{id:'brlExposure',m:'wealth',t:'Qual percentual do patrimônio financeiro está denominado em reais?',type:'single',o:[O('Até 25%',20),O('26–50%',40),O('51–75%',65),O('76–90%',83),O('Mais de 90%',95),O('Não sei',75)]},
{id:'liquidPct',m:'wealth',t:'Quanto do patrimônio pode virar dinheiro em até 30 dias sem perda relevante?',type:'single',o:[O('Até 10%',8),O('10–25%',18),O('25–50%',38),O('50–75%',63),O('75%+',85)]},
{id:'successionPlan',m:'wealth',t:'Existe planejamento sucessório estruturado?',type:'single',o:['Sim','Parcialmente','Não','Não sei'].map(x=>O(x))},
{id:'will',m:'wealth',t:'Você possui testamento válido e atualizado?',type:'single',o:['Sim','Não','Não sei','Não se aplica / não avaliei'].map(x=>O(x))},
{id:'holding',m:'wealth',t:'Existe holding ou outra estrutura patrimonial / sucessória?',type:'single',o:['Sim','Não','Em avaliação','Não sei'].map(x=>O(x))},
{id:'familyDocuments',m:'wealth',t:'Sua família sabe onde localizar contas, seguros, documentos e informações patrimoniais?',type:'single',o:['Sim','Parcialmente','Não'].map(x=>O(x))},
{id:'successionLiquidity',m:'wealth',t:'Existe liquidez reservada para custos relacionados à sucessão?',type:'single',o:['Sim','Parcialmente','Não','Não sei'].map(x=>O(x))},
{id:'multiCountryAssets',m:'wealth',t:'Você possui patrimônio em mais de um país?',type:'single',o:['Sim','Não'].map(x=>O(x))},
{id:'successionComplexity',m:'wealth',t:'Há fatores que aumentam a complexidade familiar ou patrimonial?',type:'multi',o:['Filhos de relacionamentos diferentes','Dependentes especiais','União estável','Sócios','Empresa familiar','Patrimônio internacional','Herdeiros no exterior','Nenhum'].map(x=>O(x))},

{id:'goals',m:'future',t:'Quais são hoje seus três principais objetivos financeiros?',type:'multi',limit:3,o:['Proteção da família','Independência financeira','Aposentadoria','Educação dos filhos','Crescimento patrimonial','Internacionalização','Compra de imóvel','Venda da empresa','Sucessão / legado','Morar fora'].map(x=>O(x))},
{id:'goalHorizon',m:'future',t:'Em que horizonte está o objetivo mais importante?',type:'single',o:[O('0–3 anos',2),O('3–5 anos',4),O('5–10 anos',7),O('10+ anos',12)]},
{id:'goalFunding',m:'future',t:'Quanto desse objetivo você acredita já estar financeiramente preparado para cumprir?',type:'single',o:[O('Menos de 20%',10),O('20–40%',30),O('40–60%',50),O('60–80%',70),O('Mais de 80%',90),O('Não sei',30)]},
{id:'foreignInvestments',m:'future',t:'Você possui investimentos fora do seu país de residência?',type:'single',o:['Sim','Não'].map(x=>O(x))},
{id:'foreignPct',m:'future',t:'Qual percentual aproximado do patrimônio financeiro está no exterior?',type:'single',show:a=>a.foreignInvestments==='Sim',o:[O('Até 10%',7),O('10–25%',18),O('25–50%',38),O('50%+',65)]},
{id:'foreignGoals',m:'future',t:'Existem objetivos futuros denominados em dólar ou euro?',type:'multi',o:['Educação','Moradia','Aposentadoria','Viagens','Negócios','Sucessão','Nenhum'].map(x=>O(x))},
{id:'planningFormal',m:'future',t:'Você possui hoje um planejamento financeiro formal?',type:'single',o:['Sim e reviso periodicamente','Tenho parcialmente','Já fiz, mas está desatualizado','Não'].map(x=>O(x))},
{id:'professionals',m:'future',t:'Quais profissionais participam hoje do seu planejamento?',type:'multi',o:['Planejador financeiro','Assessor de investimentos','Contador','Advogado','Corretor de seguros','Private banker','Family office','Nenhum'].map(x=>O(x))},
{id:'coordinated',m:'future',t:'Esses profissionais trabalham de forma coordenada em uma estratégia única?',type:'single',o:['Sim','Parcialmente','Não','Não sei','Não se aplica'].map(x=>O(x))},
{id:'selfScore',m:'future',t:'De 0 a 10, quão organizado você considera seu planejamento financeiro?',type:'range',min:0,max:10,step:1,why:'Compararemos sua percepção com os indicadores objetivos do assessment.'},
{id:'mainConcern',m:'future',t:'Qual preocupação mais ocupa sua cabeça hoje?',type:'single',o:['Manter meu padrão de vida','Proteger minha família','Saúde','Crescer patrimônio','Preservar patrimônio','Sucessão','Aposentadoria','Internacionalizar patrimônio','Não tenho preocupação específica'].map(x=>O(x))}
];
function visibleQuestions(){return Q.filter(q=>!q.show||q.show(state.answers))}
function save(){localStorage.setItem('pwp_answers',JSON.stringify(state.answers)); if(state.contact)localStorage.setItem('pwp_contact',JSON.stringify(state.contact))}
function logo(cls=''){return `<div class="${cls}"><img src="/pwp-logo.png" alt="PWP Wealth Solutions"></div>`}
function app(html){$('#app').innerHTML=`<div class="app">${html}</div>`; window.scrollTo(0,0)}
function landing(){app(`<main class="hero screen"><div class="hero-inner"><div class="hero-logo-wrap">${logo('')}</div><div class="eyebrow">PWP Financial Protection Assessment™</div><h1>Proteja o que realmente importa.</h1><p class="lead">Descubra, em poucos minutos, como está a blindagem financeira da sua vida e da sua família — renda, saúde, liquidez, patrimônio, sucessão e futuro em uma visão 360º.</p><div class="value-list"><div class="value"><i>360°</i><span><b>Análise completa e adaptativa</b><br><small>Você só responde o que faz sentido para o seu perfil.</small></span></div><div class="value"><i>▣</i><span><b>Resultado personalizado</b><br><small>Indicadores, gaps e insights claros para orientar sua próxima conversa.</small></span></div><div class="value"><i>✓</i><span><b>Privacidade em primeiro lugar</b><br><small>Sem dados médicos detalhados neste diagnóstico inicial.</small></span></div></div><button class="btn primary block" id="start">Iniciar meu diagnóstico <span>→</span></button><div class="fine">Diagnóstico educacional e indicativo. Resultados devem ser validados por um especialista PWP.</div></div></main>`); $('#start').onclick=()=>{state.current=0;renderQuestion()}}
function questionInput(q,v){
 if(q.type==='single')return `<div class="options">${q.o.map(o=>`<button class="option ${v===o.value?'selected':''}" data-v='${JSON.stringify(o.value)}'><span class="radio"></span><span>${o.label}</span></button>`).join('')}</div>`;
 if(q.type==='multi'){const arr=Array.isArray(v)?v:[];return `<div class="options">${q.o.map(o=>`<button class="option checkbox ${arr.includes(o.value)?'selected':''}" data-v='${JSON.stringify(o.value)}'><span class="radio"></span><span>${o.label}</span></button>`).join('')}</div>${q.limit?`<div class="fine" style="color:#6f7b87;text-align:left">Selecione até ${q.limit} opções.</div>`:''}`}
 if(q.type==='number')return `<input class="field" id="field" type="number" min="${q.min||0}" max="${q.max||999}" placeholder="${q.placeholder||''}" value="${v??''}">`;
 if(q.type==='range'){const x=v??5;return `<div class="range-row"><input id="field" type="range" min="${q.min}" max="${q.max}" step="${q.step||1}" value="${x}"><div class="range-value" id="rv">${x}/10</div></div>`}
}
function renderQuestion(){const qs=visibleQuestions(); if(state.current>=qs.length)return processing(); const q=qs[state.current],m=MODULES.find(x=>x.id===q.m), mi=MODULES.findIndex(x=>x.id===q.m)+1; const prog=((state.current)/qs.length)*100; app(`<main class="flow screen"><section class="flow-card"><header class="flow-head"><div class="flow-brand"><div class="mini-logo">${logo('')}</div><span style="font-size:11px;color:#aebdcb">CONFIDENCIAL • 360º</span></div><div class="module-label"><span>Módulo ${mi} de 8 · ${m.name}</span><span>${state.current+1}/${qs.length}</span></div><div class="progress"><span style="width:${prog}%"></span></div></header><div class="flow-body"><div class="module-chip"><span>${m.icon}</span>${m.name}</div><h1 class="qtitle">${q.t}</h1>${q.helper?`<p class="helper">${q.helper}</p>`:''}${questionInput(q,state.answers[q.id])}${q.why?`<div class="why"><strong>Por que perguntamos?</strong><br>${q.why}</div>`:''}<div class="flow-actions"><button class="btn ghost back" id="back">‹</button><button class="btn dark" id="next">Continuar <span>→</span></button></div></div></section></main>`);
 const next=$('#next'),back=$('#back'); back.disabled=state.current===0; back.onclick=()=>{if(state.current>0){state.current--;renderQuestion()}};
 if(q.type==='single')$$('.option').forEach(el=>el.onclick=()=>{state.answers[q.id]=JSON.parse(el.dataset.v);save();renderQuestion()});
 if(q.type==='multi')$$('.option').forEach(el=>el.onclick=()=>{let arr=Array.isArray(state.answers[q.id])?[...state.answers[q.id]]:[];const val=JSON.parse(el.dataset.v); if(arr.includes(val))arr=arr.filter(x=>x!==val);else {if(q.limit&&arr.length>=q.limit)return; if(val==='Não'||val==='Nenhum')arr=[val]; else arr=arr.filter(x=>x!=='Não'&&x!=='Nenhum').concat(val)} state.answers[q.id]=arr;save();renderQuestion()});
 if(q.type==='range')$('#field').oninput=e=>{$('#rv').textContent=`${e.target.value}/10`};
 next.onclick=()=>{if(q.type==='number'){const x=+$('#field').value;if(!x)return;state.answers[q.id]=x}else if(q.type==='range')state.answers[q.id]=+$('#field').value; if(state.answers[q.id]===undefined||state.answers[q.id]===null||(Array.isArray(state.answers[q.id])&&!state.answers[q.id].length))return;save();state.current++;renderQuestion()}
}
function compute(){const a=state.answers; const income=+a.income||0, expenses=+a.expenses||0, liquid=+a.liquidAssets||0, indep=+a.independentIncome||0, disability=+a.disabilityMonthly||0, life=+a.lifeCapital||0, debt=+a.debtAmount||0, nw=+a.netWorth||0;
 const runway=expenses?liquid/expenses:0; const dep=income?clamp((1-indep/income)*100):(+a.workDependency||50); const incomeGap=Math.max(0,expenses-indep-disability); const years=+a.familyYears||5; let familyNeed=expenses*12*years+debt; if((a.protectedGoals||[]).includes('Educação dos filhos'))familyNeed+=1000000; if((a.protectedGoals||[]).includes('Moradia'))familyNeed+=500000; if((a.protectedGoals||[]).includes('Suporte aos pais'))familyNeed+=500000; const familyGap=Math.max(0,familyNeed-liquid-life);
 let incomeProtection=100; incomeProtection-=dep*.45; incomeProtection-=incomeGap/(expenses||1)*35; if(a.disabilityCover==='Não')incomeProtection-=15;if(a.disabilityCover==='Não sei')incomeProtection-=8; incomeProtection=clamp(incomeProtection);
 let familyProtection=100; const hasDeps=(a.dependents||[]).some(x=>x!=='Ninguém'); if(hasDeps){familyProtection-=Math.min(45,familyGap/Math.max(familyNeed,1)*50);if(a.lifeCover==='Não')familyProtection-=20;if(a.beneficiaries==='Não')familyProtection-=8;if(['Mais de 5 anos','Nunca'].includes(a.lifeReview))familyProtection-=8}else familyProtection=80;
 let liquidity=clamp(runway/12*75+25); if(a.emergencyReserve==='Não')liquidity-=12;if(a.restrictedLiquidity==='Sim')liquidity-=10;if(debt>liquid*2)liquidity-=10; liquidity=clamp(liquidity);
 let health=55;if(['Seguro internacional','Plano nacional + internacional'].includes(a.healthPlan))health+=25;else if(['Plano nacional','Plano nacional premium'].includes(a.healthPlan))health+=12;else health-=18;if(a.globalHealth==='Sim, globalmente')health+=15;if(a.medicalLiquidity==='Sim, confortavelmente')health+=10;if(['Provavelmente não','Não'].includes(a.medicalLiquidity))health-=15;health=clamp(health);
 let wealth=75; wealth-=Math.max(0,(+a.businessConcentration||0)-40)*.45; wealth-=Math.max(0,(+a.brazilConcentration||0)-70)*.35; if((+a.liquidPct||0)<25)wealth-=15; wealth=clamp(wealth);
 let succession=25;if(a.successionPlan==='Sim')succession+=35;if(a.successionPlan==='Parcialmente')succession+=18;if(a.will==='Sim')succession+=10;if(a.familyDocuments==='Sim')succession+=10;if(a.successionLiquidity==='Sim')succession+=12;if(a.holding==='Sim')succession+=8;if(a.multiCountryAssets==='Sim'&&a.successionPlan!=='Sim')succession-=10;succession=clamp(succession);
 let future=35+(+a.goalFunding||30)*.45;if(a.planningFormal==='Sim e reviso periodicamente')future+=18;if(a.planningFormal==='Tenho parcialmente')future+=8;if(a.coordinated==='Sim')future+=10;if(a.coordinated==='Não')future-=5;future=clamp(future);
 let intl=25;const foreign=+a.foreignPct||0;intl+=Math.min(35,foreign*.7); const bg=+a.brazilConcentration||0,brl=+a.brlExposure||0;intl-=Math.max(0,bg-75)*.35;intl-=Math.max(0,brl-75)*.25;if((a.foreignGoals||[]).some(x=>x!=='Nenhum')&&a.foreignInvestments==='Não')intl-=12;intl=clamp(intl);
 const pillars={incomeProtection,familyProtection,liquidity,health,wealth,succession,future,intl}; const weights={incomeProtection:.18,familyProtection:.18,liquidity:.14,health:.12,wealth:.10,succession:.12,future:.08,intl:.08}; let score=Math.round(Object.keys(pillars).reduce((s,k)=>s+pillars[k]*weights[k],0));
 const priority=clamp(Math.round((100-score)*.55+(nw>=5000000?12:0)+(nw>=20000000?8:0)+(familyGap>1000000?10:0)+(incomeGap>10000?10:0)+(a.successionPlan!=='Sim'?6:0)+(a.mainConcern&&a.mainConcern!=='Não tenho preocupação específica'?4:0)));
 const insights=[]; insights.push({title:'Sua renda é um dos principais ativos da família',text:`Aproximadamente ${pct(dep)} da renda familiar informada depende da sua capacidade de geração de renda. O gap mensal indicativo em um cenário de incapacidade é ${money(incomeGap)}.`});
 if(hasDeps)insights.push({title:'Existe um potencial gap de proteção familiar',text:`Com as premissas informadas, o modelo estima uma diferença de aproximadamente ${money(familyGap)} entre necessidades familiares e recursos/coberturas identificados.`});
 const concentration=Math.max(+a.brazilConcentration||0,+a.businessConcentration||0); insights.push({title:'Concentração patrimonial merece análise',text:`A maior concentração declarada é de aproximadamente ${pct(concentration)}. Concentração não significa inadequação, mas é um ponto importante para o planejamento global.`});
 return {score,priority,pillars,runway,dep,incomeGap,familyGap,familyNeed,netWorth:nw,income,expenses,insights:insights.slice(0,3)}
}
function processing(){state.results=compute();app(`<main class="processing"><div class="processing-card">${logo('hero-logo-wrap')}<div class="ring" style="--pct:100"><span>100%</span></div><h1>Diagnóstico concluído</h1><p style="color:#c7d3de;line-height:1.5">Estamos organizando suas respostas e calculando os indicadores do seu relatório personalizado.</p><div class="process-list"><div><b>✓</b> Calculando seus indicadores</div><div><b>✓</b> Identificando gaps prioritários</div><div><b>✓</b> Preparando seus insights</div><div><b>✓</b> Organizando a visão 360º</div></div><p style="font-family:Georgia,serif;font-size:20px">“Planejamento hoje. Tranquilidade sempre.”</p></div></main>`);setTimeout(()=>capture(),900)}
function capture(){app(`<main class="capture"><section class="capture-card"><div class="capture-head">${logo('hero-logo-wrap')}<h1>Seu relatório está pronto.</h1><p style="color:#d4dfe9;line-height:1.5">Confirme seus dados para acessar a análise completa e, se desejar, conversar com um especialista PWP.</p></div><div class="capture-body"><div class="field-group"><input class="field" id="name" placeholder="Nome completo" value="${state.contact?.name||''}"><input class="field" id="email" type="email" placeholder="E-mail" value="${state.contact?.email||''}"><input class="field" id="phone" placeholder="WhatsApp com DDD" value="${state.contact?.phone||''}"><input class="field" id="city" placeholder="Cidade / País" value="${state.contact?.city||''}"><label class="consent"><input id="consent" type="checkbox"><span>Autorizo o tratamento dos dados informados para gerar meu diagnóstico, permitir contato relacionado à análise e apoiar a continuidade do atendimento PWP. Posso solicitar correção ou exclusão pelos canais oficiais.</span></label><button class="btn dark block" id="report">Acessar meu relatório →</button><button class="btn ghost block" id="backq">Voltar ao diagnóstico</button></div><p class="disclaimer">Este assessment é educacional e indicativo. Não constitui recomendação individual de investimento, tributária, jurídica, médica ou de contratação de seguros. <a href="${CONFIG.websiteUrl}" target="_blank" rel="noopener">Conheça a PWP</a>.</p></div></section></main>`);$('#backq').onclick=()=>{state.current=Math.max(0,visibleQuestions().length-1);renderQuestion()};$('#report').onclick=async()=>{const contact={name:$('#name').value.trim(),email:$('#email').value.trim(),phone:$('#phone').value.trim(),city:$('#city').value.trim()};if(!contact.name||!contact.phone||!$('#consent').checked)return alert('Informe nome, WhatsApp e aceite o consentimento para continuar.');state.contact=contact;save();state.results=compute();try{await fetch(CONFIG.leadApi,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contact,referral:state.ref,answers:state.answers,results:state.results})})}catch{}renderResult()}}
const pillarNames={incomeProtection:'Proteção de Renda',familyProtection:'Proteção Familiar',liquidity:'Liquidez',health:'Saúde',wealth:'Patrimônio',succession:'Sucessão',future:'Futuro / Objetivos',intl:'Diversificação Internacional'};
function status(score){return score>=80?'Estruturado':score>=60?'Atenção':score>=40?'Vulnerabilidade':'Prioridade'}
function barColor(v){return v>=80?'var(--ok)':v>=60?'var(--warn)':v>=40?'var(--orange)':'var(--risk)'}
function renderResult(tab='summary'){const r=state.results||compute();const body=tab==='summary'?summaryPanel(r):tab==='pillars'?pillarsPanel(r):tab==='scenarios'?scenarioPanel(r):actionPanel(r);app(`<main class="result"><div class="result-hero"><div class="result-wrap"><div class="result-top"><div class="result-logo">${logo('')}</div><button class="smallbtn no-print" onclick="window.print()">PDF / Imprimir</button></div><div class="score-box"><div class="score-title">Seu Índice de Blindagem Financeira</div><div class="score-gauge" style="--score:${r.score}"><div class="score-num">${r.score}<small>/100</small></div></div><div class="score-status">${status(r.score)}</div><p class="score-copy">${r.score>=80?'Sua estrutura demonstra bom nível de proteção, com oportunidades pontuais de otimização.':r.score>=60?'Sua estrutura possui bases importantes, mas há pontos que merecem revisão.':'Identificamos lacunas relevantes que merecem ser validadas em uma análise personalizada.'}</p></div></div></div><div class="result-main">${body}<p class="disclaimer">Valores e gaps são estimativas baseadas nas respostas e premissas do assessment. Não representam recomendação automática de produto. A validação deve ocorrer com profissional habilitado, considerando documentação e contexto completo.</p></div><nav class="sticky-nav no-print"><div class="nav-inner"><button class="nav-btn ${tab==='summary'?'active':''}" data-tab="summary"><b>⌂</b>Resumo</button><button class="nav-btn ${tab==='pillars'?'active':''}" data-tab="pillars"><b>▥</b>Pilares</button><button class="nav-btn ${tab==='scenarios'?'active':''}" data-tab="scenarios"><b>◈</b>Simular</button><button class="nav-btn ${tab==='action'?'active':''}" data-tab="action"><b>→</b>Próximo passo</button></div></nav></main>`);$$('.nav-btn').forEach(b=>b.onclick=()=>renderResult(b.dataset.tab))}
function summaryPanel(r){return `<section class="panel"><h2>Seus números</h2><div class="kpis"><div class="kpi"><strong>${money(r.income)}</strong><span>Renda familiar estimada</span></div><div class="kpi"><strong>${pct(r.dep)}</strong><span>Dependência da renda</span></div><div class="kpi"><strong>${r.runway.toFixed(1)} meses</strong><span>Runway de liquidez</span></div><div class="kpi"><strong>${money(r.familyGap)}</strong><span>Gap familiar indicativo</span></div></div></section><section class="panel"><h2>Principais insights</h2>${r.insights.map((x,i)=>`<div class="insight"><div class="n">0${i+1}</div><div><h3>${x.title}</h3><p>${x.text}</p></div></div>`).join('')}</section><section class="panel scenario"><h2>Prioridade inicial</h2><p>O modelo identificou <b>${status(r.score).toLowerCase()}</b> como nível geral do assessment. Revise os pilares para entender onde concentrar a conversa.</p><button class="btn dark block" onclick="window.pwpTab('pillars')">Ver análise por pilar →</button></section>`}
function pillarsPanel(r){return `<section class="panel"><h2>Resultado por pilar</h2>${Object.entries(r.pillars).map(([k,v])=>`<div class="pillar"><div><div class="pillar-name">${pillarNames[k]}</div><div class="bar"><span style="width:${v}%;background:${barColor(v)}"></span></div></div><div class="snum">${Math.round(v)}</div></div>`).join('')}</section><section class="panel"><h2>Como interpretar</h2><p class="helper" style="margin:0"><b>80–100</b> Estruturado · <b>60–79</b> Atenção · <b>40–59</b> Vulnerabilidade · <b>0–39</b> Prioridade. Um score baixo indica um ponto a validar; não significa automaticamente que um produto específico seja necessário.</p></section>`}
function scenarioPanel(r){return `<section class="panel scenario"><h2>E se você ficasse 12 meses sem trabalhar?</h2><p>Com as informações declaradas, estimamos:</p><div class="pillar"><span>Renda familiar atual</span><b>${money(r.income)}</b></div><div class="pillar"><span>Renda independente estimada</span><b>${money(+state.answers.independentIncome||0)}</b></div><div class="pillar"><span>Cobertura mensal informada</span><b>${money(+state.answers.disabilityMonthly||0)}</b></div><div class="big">${money(r.incomeGap)} <small style="font-size:13px">/mês</small></div><p class="helper">Déficit mensal indicativo antes do uso de reservas. Sua liquidez atual representa cerca de <b>${r.runway.toFixed(1)} meses</b> do padrão de despesas informado.</p></section><section class="panel scenario"><h2>E se sua renda deixasse de sustentar sua família?</h2><div class="pillar"><span>Necessidade familiar modelada</span><b>${money(r.familyNeed)}</b></div><div class="pillar"><span>Recursos líquidos</span><b>${money(+state.answers.liquidAssets||0)}</b></div><div class="pillar"><span>Seguro de vida informado</span><b>${money(+state.answers.lifeCapital||0)}</b></div><div class="big">${money(r.familyGap)}</div><p class="helper">Gap indicativo para discussão. A modelagem utiliza o horizonte de manutenção familiar e objetivos declarados, sem substituir análise atuarial, jurídica ou financeira completa.</p></section>`}
function actionPanel(r){const top=(r.insights||[]).slice(0,3).map(x=>x.title).join(' | ');const who=state.contact?.name?` Meu nome é ${state.contact.name}.`:'';const msg=encodeURIComponent(`Olá, PWP.${who} Concluí o Financial Protection Assessment. Meu índice foi ${r.score}/100. Principais pontos: ${top}. Gostaria de revisar meu diagnóstico com um especialista.`);const wa=`https://wa.me/${CONFIG.whatsappNumber}?text=${msg}`;return `<section class="panel"><h2>Converse com um especialista PWP</h2><p class="helper">Seu assessment organiza os pontos que merecem validação. A conversa com o especialista serve para revisar premissas, complementar dados e explorar estratégias adequadas ao seu contexto.</p><a class="btn primary block" style="text-decoration:none;text-align:center" href="${wa}" target="_blank" rel="noopener">Agendar conversa pelo WhatsApp →</a><a class="btn dark block" style="margin-top:10px;text-decoration:none;text-align:center" href="${CONFIG.contactUrl}" target="_blank" rel="noopener">Outros canais de contato</a><button class="btn ghost block" style="margin-top:10px" onclick="window.print()">Baixar / imprimir relatório em PDF</button></section><section class="panel"><h2>Resumo para sua conversa</h2><p class="helper" style="margin:0">Leve para a reunião: documentos de coberturas atuais, visão de ativos e passivos, despesas familiares, estruturas societárias e sucessórias relevantes e seus objetivos prioritários. Isso permite validar os indicadores com maior precisão.</p></section>`}
window.pwpTab=t=>renderResult(t);
function advisorLogin(){app(`<main class="advisor-login"><section class="login-card">${logo('')}<h1>Área do Consultor</h1><p class="helper">Acesse os leads do PWP Financial Protection Assessment.</p><input class="field" id="pin" type="password" placeholder="PIN administrativo"><button class="btn dark block" id="login" style="margin-top:10px">Entrar</button><button class="btn ghost block" id="home" style="margin-top:10px">Voltar</button><p class="fine">Na versão local, o PIN padrão é 2026. Em produção, configure PWP_ADMIN_PIN no servidor.</p></section></main>`);$('#home').onclick=landing;$('#login').onclick=()=>loadAdvisor($('#pin').value)}
async function loadAdvisor(pin,filter='Todos'){let leads=[];try{const j=await fetch(CONFIG.leadApi,{headers:{'x-admin-pin':pin}}).then(r=>r.json());if(!j.ok)throw 0;leads=j.leads}catch{return alert('PIN inválido ou servidor indisponível.')}const rows=leads.filter(x=>filter==='Todos'||priorityClass(x.results?.priority)===filter);app(`<main class="advisor"><header class="advisor-head"><div class="advisor-head-inner"><div style="background:#fff;border-radius:10px;padding:5px 8px">${logo('')}</div><div class="toolbar"><button class="smallbtn" id="export">Exportar CSV</button><button class="smallbtn" id="logout">Sair</button></div></div></header><div class="advisor-main"><h1>Leads qualificados</h1><p class="helper">Diagnósticos concluídos, ordenados por data. Priority Score é interno e não aparece ao cliente.</p><div class="filters">${['Todos','A','B','C'].map(x=>`<button class="chip ${filter===x?'active':''}" data-f="${x}">${x==='Todos'?'Todos':`Prioridade ${x}`}</button>`).join('')}</div><div id="leads">${rows.length?rows.map(leadCard).join(''):'<div class="empty">Nenhum lead nesta faixa ainda.</div>'}</div></div></main>`);$$('.chip').forEach(b=>b.onclick=()=>loadAdvisor(pin,b.dataset.f));$('#logout').onclick=landing;$('#export').onclick=()=>exportCSV(leads)}
function priorityClass(p=0){return p>=70?'A':p>=50?'B':'C'}
function leadCard(l){const r=l.results||{},a=l.answers||{},c=l.contact||{},pc=priorityClass(r.priority);return `<article class="lead-card"><div class="lead-head"><div><div class="lead-name">${esc(c.name||'Lead')}</div><div class="lead-meta">${esc(c.city||'')} · ${new Date(l.createdAt).toLocaleString('pt-BR')} · Origem: ${esc(l.referral||'organic')}</div></div><span class="badge ${pc.toLowerCase()}">Prioridade ${pc} · ${r.priority||0}</span></div><div class="lead-grid"><div class="lead-kpi"><strong>${r.score||'—'}/100</strong><span>Índice PWP</span></div><div class="lead-kpi"><strong>${money(r.netWorth)}</strong><span>Patrimônio estimado</span></div><div class="lead-kpi"><strong>${money(r.incomeGap)}</strong><span>Gap renda / mês</span></div><div class="lead-kpi"><strong>${money(r.familyGap)}</strong><span>Gap familiar</span></div></div><div class="lead-gaps"><b>Perfil:</b> ${esc(a.occupation||'—')} · ${esc(a.marital||'—')}<br><b>Contato:</b> ${esc(c.phone||'—')} · ${esc(c.email||'—')}<br><b>Insights:</b> ${(r.insights||[]).map(x=>esc(x.title)).join(' • ')}</div><div class="toolbar" style="margin-top:12px"><a class="smallbtn" style="text-decoration:none;color:inherit" href="https://wa.me/${String(c.phone||'').replace(/\D/g,'')}" target="_blank">WhatsApp</a><button class="smallbtn" onclick='navigator.clipboard.writeText(${JSON.stringify(JSON.stringify(r.insights||[]))})'>Copiar insights</button></div></article>`}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function exportCSV(leads){const rows=[['Data','Nome','Telefone','Email','Cidade','Origem','Indice','Prioridade','Patrimonio','Gap Renda','Gap Familiar'],...leads.map(l=>[l.createdAt,l.contact?.name,l.contact?.phone,l.contact?.email,l.contact?.city,l.referral,l.results?.score,l.results?.priority,l.results?.netWorth,l.results?.incomeGap,l.results?.familyGap])];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n');const b=new Blob(['\ufeff'+csv],{type:'text/csv'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='pwp-leads.csv';a.click();URL.revokeObjectURL(u)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
if(location.hash==='#advisor')advisorLogin(); else if(state.contact&&Object.keys(state.answers).length>20){state.results=compute();renderResult()}else landing();
